cmake_minimum_required(VERSION 3.24)

OPTION(BITBOT_TYPE_EFC "Enable EFC" ON)
OPTION(BITBOT_TYPE_MJ "Disable MJ" OFF)
OPTION(BITBOT_TYPE_GZ "Disable GZ" OFF)
OPTION(BITBOT_TYPE_CIFX "Disable CIFX" OFF)
MARK_AS_ADVANCED(BITBOT_TYPE_EFC BITBOT_TYPE_MJ BITBOT_TYPE_GZ BITBOT_TYPE_CIFX)

SET(PUGIXML_PUBLIC_DEFINITIONS
  $<$<BOOL:${BITBOT_TYPE_EFC}>:BITBOT_TYPE_EFC>
  $<$<BOOL:${BITBOT_TYPE_MJ}>:BITBOT_TYPE_MJ>
  $<$<BOOL:${BITBOT_TYPE_GZ}>:BITBOT_TYPE_GZ>
  $<$<BOOL:${BITBOT_TYPE_CIFX}>:BITBOT_TYPE_CIFX>
  )


SET(BITBOT_TYPE)
IF (BITBOT_TYPE_EFC)
  SET(BITBOT_TYPE "efc")
ENDIF(BITBOT_TYPE_EFC)

IF(${BITBOT_TYPE} STREQUAL "")
  return("No robot type selected")
ENDIF(${BITBOT_TYPE} STREQUAL "")

OPTION(FRONTEND_TYPE_ROS "Enable ROS" ON)
OPTION(FRONTEND_TYPE_WS "Enable WS" OFF)

SET(FRONTEND_TYPE)
IF (FRONTEND_TYPE_ROS)
  SET(FRONTEND_TYPE "ros")
ELSEIF(FRONTEND_TYPE_WS)
  SET(FRONTEND_TYPE "ws")
ENDIF()

# OPTION(BACKEND_COMM_WS "comm with ws" OFF)
# MARK_AS_ADVANCED(BACKEND_COMM_WS)
# MESSAGE(STATUS "KERNEL 0: ${BACKEND_COMM_WS} and val: " $<$<BOOL:${BACKEND_COMM_WS}>:GOD>)
# IF (${BACKEND_COMM_WS})
# MESSAGE(STATUS "KERNEL 1: ${BACKEND_COMM_WS} and val: " $<$<BOOL:${BACKEND_COMM_WS}>:GOD>)
# ELSE()
# MESSAGE(STATUS "KERNEL 2: ${BACKEND_COMM_WS} and val: " $<$<BOOL:${BACKEND_COMM_WS}>:GOD>)
# ENDIF()
# MESSAGE(STATUS "KERNEL 3: ${BACKEND_COMM_WS} and val: " $<$<BOOL:${BACKEND_COMM_WS}>:GOD>)
